generation:
  num_subsamples: 5
  num_demos: 5
  num_prompts_per_subsample: 50
  model:
    name: VertexAI_forward
    batch_size: 500
    gpt_config:
      model_name: text-bison
      temperature: 0.9
      max_output_tokens: 50
      top_p: 0.9
evaluation:
  num_samples: 50
  num_few_shot: 5
  model:
    name: VertexAI_forward
    batch_size: 500
    gpt_config:
      model: text-bison
      temperature: 0.0
      max_tokens: 200
demo:
  model:
    name: VertexAI_forward
    batch_size: 500
    gpt_config:
      model: text-bison
      temperature: 0.0
      max_tokens: 200
